// ...existing code...
using MonitorizareAngajati.Services;
// ...existing code...
public void ConfigureServices(IServiceCollection services)
{
    // ...existing code...
    services.AddScoped<EmployeeService>();
    // ...existing code...
}
// ...existing code...
